### ISSUE TITLE
Connection errors

### ISSUE THREAD

**Issue by theseal** [stockholmuniversity/Nagios-NRPE#16]
1.0.2 doesn't handle timeouts (and possible other connection errors?) and dies. Easy to reproduce with included `check_nrpe.pl`.

```
/usr/bin/check_nrpe.pl -H example.com -c check_disk
Not a GLOB reference at /usr/share/perl5/Nagios/NRPE/Client.pm line 241.
```

`check_nrpe.pl` in 1.0.0 didn't have any error checking but it doesn't die in the lib but returns an undef buffer (which is OK…):
```
/usr/bin/check_nrpe.pl -H example.com -c check_disk
Use of uninitialized value in concatenation (.) or string at /usr/bin/check_nrpe.pl line 89.
```

Stole the error handling from 1.0.2 to and patched my local  1.0.0 and that works fine (didn't die):
```
/usr/bin/check_nrpe.pl.mod -H example.com -c check_disk
Socket error:IO::Socket::INET: connect: timeout
```

**Comment by mickenordin** [comment]
This seems to be in the code in Client.pm that tries to establish a tls connection. With the -n option the error message is better. I will see if I can hunt it down and fix a better error message for when it cant establish a tls socket.
